name: Deploy SPFx Solution on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build and bundle
        run: |
          npx gulp build --ship
          npx gulp bundle --ship

      - name: Package solution
        run: npx gulp package-solution --ship

      - name: Install Office 365 CLI
        run: npm install -g @pnp/cli-microsoft365

      - name: Deploy to SharePoint App Catalog
        env:
          M365_CLIENT_ID: ${{ secrets.M365_CLIENT_ID }}
          M365_CLIENT_SECRET: ${{ secrets.M365_CLIENT_SECRET }}
          M365_TENANT_ID: ${{ secrets.M365_TENANT_ID }}
          APP_CATALOG_URL: ${{ secrets.APP_CATALOG_URL }}
        run: |
          echo "Logging in with service principal..."
          m365 login --authType clientSecret --clientId "$M365_CLIENT_ID" --clientSecret "$M365_CLIENT_SECRET" --tenant "$M365_TENANT_ID"
          
          echo "Adding app to catalog..."
          m365 spo app add -p sharepoint/solution/*.sppkg --overwrite --appCatalogUrl "$APP_CATALOG_URL"
          
          echo "Getting app ID for deployment..."
          APP_ID=$(m365 spo app list --appCatalogUrl "$APP_CATALOG_URL" --output json | jq -r '.[] | select(.Name | contains("monarch-sidenav")) | .ID')
          echo "Deploying appId: $APP_ID"
          
          echo "Deploying app..."
          m365 spo app deploy --appId "$APP_ID" --appCatalogUrl "$APP_CATALOG_URL" --scope tenant --wait
          
          echo "Deployment completed successfully!"

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spfx-solution
          path: sharepoint/solution/*.sppkg 